// <auto-generated />
using System;
using BusinessLogicLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessLogicLayer.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20260715065403_t1111")]
    partial class t1111
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogicLayer.Models.Orders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T1", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("t1tbl");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Email")
                        .HasColumnType("int");

                    b.Property<int>("T1ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("T1ID")
                        .IsUnique();

                    b.ToTable("t2tbl");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T3", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("t3tbl");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T4", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Email")
                        .HasColumnType("int");

                    b.Property<int>("T3ID")
                        .HasColumnType("int");

                    b.Property<int?>("abovetable")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("abovetable")
                        .IsUnique()
                        .HasFilter("[abovetable] IS NOT NULL");

                    b.ToTable("t4tbl");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.Valid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Mobile");

                    b.ToTable("UserTable");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T2", b =>
                {
                    b.HasOne("BusinessLogicLayer.Models.T1", "T1Data")
                        .WithOne("T2Data")
                        .HasForeignKey("BusinessLogicLayer.Models.T2", "T1ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("T1Data");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T4", b =>
                {
                    b.HasOne("BusinessLogicLayer.Models.T3", "T3Data")
                        .WithOne("T4Data")
                        .HasForeignKey("BusinessLogicLayer.Models.T4", "abovetable");

                    b.Navigation("T3Data");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T1", b =>
                {
                    b.Navigation("T2Data");
                });

            modelBuilder.Entity("BusinessLogicLayer.Models.T3", b =>
                {
                    b.Navigation("T4Data");
                });
#pragma warning restore 612, 618
        }
    }
}
